// Keeps the skill's version in step across SKILL.md, quest.py and the published
// skills/quest-log/version.json, which assistants check to know their copy is stale.
//   node shared/scripts/skill-version.mjs --bump    after editing SKILL.md or quest.py
//   node shared/scripts/skill-version.mjs --check   fails if they disagree or the files changed without a bump
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '../..');
const dir = join(root, 'skills/quest-log');
const paths = { skill: join(dir, 'SKILL.md'), script: join(dir, 'scripts/quest.py'), version: join(dir, 'version.json') };
const SITE = 'https://tasks.patrick-mckinley.com/';
const SKILL_RE = /^\*\*Skill version: (\d+)\*\*/m;
const SCRIPT_RE = /^SKILL_VERSION = (\d+)$/m;

const read = () => ({ skill: readFileSync(paths.skill, 'utf8'), script: readFileSync(paths.script, 'utf8') });
/** Fingerprint of the two files an assistant actually runs. */
const fingerprint = ({ skill, script }) => createHash('sha256').update(skill).update('\0').update(script).digest('hex');
const versions = ({ skill, script }) => [Number(SKILL_RE.exec(skill)?.[1]), Number(SCRIPT_RE.exec(script)?.[1])];

function check() {
  const files = read();
  const meta = JSON.parse(readFileSync(paths.version, 'utf8'));
  const [inSkill, inScript] = versions(files);
  const problems = [];
  if (!inSkill) problems.push('SKILL.md has no "**Skill version: N**" line');
  if (!inScript) problems.push('quest.py has no "SKILL_VERSION = N" line');
  if (inSkill !== meta.version || inScript !== meta.version)
    problems.push(`versions disagree: version.json ${meta.version}, SKILL.md ${inSkill}, quest.py ${inScript}`);
  if (meta.fingerprint !== fingerprint(files)) problems.push('SKILL.md or quest.py changed without a version bump');
  return problems;
}

if (process.argv.includes('--bump')) {
  const meta = JSON.parse(readFileSync(paths.version, 'utf8'));
  const next = meta.version + 1;
  const files = read();
  files.skill = files.skill.replace(SKILL_RE, `**Skill version: ${next}**`);
  files.script = files.script.replace(SCRIPT_RE, `SKILL_VERSION = ${next}`);
  writeFileSync(paths.skill, files.skill);
  writeFileSync(paths.script, files.script);
  const out = {
    $comment: 'GENERATED by `npm run skill:version`. Assistants compare `version` with the one in their SKILL.md and reload the skill when this is higher.',
    name: 'quest-log',
    version: next,
    released: new Date().toISOString().slice(0, 10),
    skill: `${SITE}skills/quest-log/SKILL.md`,
    script: `${SITE}skills/quest-log/scripts/quest.py`,
    schemas: `${SITE}schema/index.json`,
    fingerprint: fingerprint(files),
  };
  writeFileSync(paths.version, JSON.stringify(out, null, 2) + '\n');
  console.log(`Skill version ${next}`);
} else {
  const problems = check();
  if (problems.length) {
    for (const p of problems) console.error(`✗ ${p}`);
    console.error('Run `npm run skill:version` to bump the skill version.');
    process.exit(1);
  }
  console.log('✓ skill version is consistent');
}
