// Original pixel art, drawn as character maps. One char = one pixel; '.' = transparent.
// Colours come from PALETTE, with per-theme overrides for ground/sky (see THEMES).

import type { Theme } from '@quest/shared';

export const PALETTE: Record<string, string> = {
  k: '#1a1c2c', // outline
  w: '#f4f4f4',
  r: '#e43b44',
  R: '#a22633',
  o: '#f77622',
  y: '#feae34',
  Y: '#c67a14',
  u: '#fee761', // highlight yellow
  g: '#63c74d',
  G: '#265c42',
  h: '#3e8948',
  b: '#0099db',
  B: '#124e89',
  s: '#ead4aa',
  S: '#e4a672',
  n: '#b86f50',
  N: '#743f39',
  l: '#c0cbdc',
  m: '#8b9bb4',
  M: '#5a6988',
  p: '#b55088',
  P: '#68386c',
  c: '#2ce8f5',
  C: '#0095a8',
  q: '#f6757a',
  // Theme slots, overridden per theme:
  T: '#63c74d', // ground top
  t: '#3e8948', // ground top shade
  D: '#b86f50', // dirt
  d: '#743f39', // dirt shade
};

export interface ThemeColors {
  sky: string;
  skyLow: string;
  hill: string;
  hillShade: string;
  T: string;
  t: string;
  D: string;
  d: string;
  island: string;
}

export const THEMES: Record<Theme | 'warp' | 'under', ThemeColors> = {
  grass: { sky: '#5c94fc', skyLow: '#9cc3ff', hill: '#3e8948', hillShade: '#265c42', T: '#63c74d', t: '#3e8948', D: '#b86f50', d: '#743f39', island: '#63c74d' },
  desert: { sky: '#f7b267', skyLow: '#fde2a7', hill: '#d77643', hillShade: '#a8552c', T: '#fee761', t: '#e8b796', D: '#e4a672', d: '#b86f50', island: '#fee761' },
  water: { sky: '#2ce8f5', skyLow: '#b3f5fb', hill: '#0095a8', hillShade: '#124e89', T: '#f4f4f4', t: '#c0cbdc', D: '#0099db', d: '#124e89', island: '#2ce8f5' },
  ice: { sky: '#9badb7', skyLow: '#dfe9f0', hill: '#c0cbdc', hillShade: '#8b9bb4', T: '#f4f4f4', t: '#c0cbdc', D: '#8b9bb4', d: '#5a6988', island: '#f4f4f4' },
  sky: { sky: '#8fd3ff', skyLow: '#e6f6ff', hill: '#f4f4f4', hillShade: '#c0cbdc', T: '#f4f4f4', t: '#c0cbdc', D: '#dfe9f0', d: '#9badb7', island: '#f4f4f4' },
  castle: { sky: '#262b44', skyLow: '#5a2a3a', hill: '#3a4466', hillShade: '#262b44', T: '#8b9bb4', t: '#5a6988', D: '#3a4466', d: '#262b44', island: '#5a6988' },
  // A dependency's sub-level: underground, below the warp pipe.
  under: { sky: '#0b0d17', skyLow: '#1c2541', hill: '#262b44', hillShade: '#1a1c2c', T: '#0099db', t: '#124e89', D: '#3a4466', d: '#262b44', island: '#3a4466' },
  warp: { sky: '#1a1c2c', skyLow: '#3b1d53', hill: '#68386c', hillShade: '#3b1d53', T: '#b55088', t: '#68386c', D: '#3b1d53', d: '#1a1c2c', island: '#b55088' },
};

type Map = string[];

const HERO_TOP = [
  '................',
  '.....kkkkkk.....',
  '....kccccccck...',
  '...kcccCCccck...',
  '...kcCssssCck...',
  '...kcswkswkck...',
  '...kcsskssssk...',
  '....kcsqqssk....',
  '....koooooook...',
];

export const SPRITES: Record<string, Map> = {
  hero: [
    ...HERO_TOP,
    '...kbbbboobbbk..',
    '..ksbbbbobbbbsk.',
    '..ksbbbbbbbbbsk.',
    '...kbbbbbbbbbk..',
    '....kbbk.kbbk...',
    '...kNNNk.kNNNk..',
    '...kkkk...kkkk..',
  ],
  'hero-walk': [
    ...HERO_TOP,
    '...kbbbboobbbk..',
    '..ksbbbbobbbbk..',
    '..kkbbbbbbbbbsk.',
    '...kbbbbbbbbbsk.',
    '...kbbk..kbbkk..',
    '..kNNNk...kNNNk.',
    '..kkkk.....kkkk.',
  ],
  'hero-jump': [
    '..kk........kk..',
    '.ksk.kkkkkk.ksk.',
    '.kskkccccccckskk',
    '..kkcccCCccck...',
    '...kcCssssCck...',
    '...kcswkswkck...',
    '...kcsskssssk...',
    '....kcsqqssk....',
    '....koooooook...',
    '...kbbbboobbbk..',
    '...kbbbbobbbbk..',
    '...kbbbbbbbbbk..',
    '...kbbbbbbbbbk..',
    '...kbbk..kbbk...',
    '..kNNNk..kNNNk..',
    '..kkkk....kkkk..',
  ],
  qblock: [
    'kkkkkkkkkkkkkkkk',
    'kuyyyyyyyyyyyyYk',
    'kyNyyyyyyyyyyNYk',
    'kyyyyykkkkyyyyYk',
    'kyyyykuuuukyyyYk',
    'kyyyykuYYukyyyYk',
    'kyyyyykkYukyyyYk',
    'kyyyyyyykukyyyYk',
    'kyyyyyykuukyyyYk',
    'kyyyyyykuYkyyyYk',
    'kyyyyyyykkyyyyYk',
    'kyyyyyykuukyyyYk',
    'kyyyyyykuYkyyyYk',
    'kyNyyyyykkyyyyNk',
    'kYYYYYYYYYYYYYYk',
    'kkkkkkkkkkkkkkkk',
  ],
  used: [
    'kkkkkkkkkkkkkkkk',
    'knnnnnnnnnnnnnNk',
    'knNnnnnnnnnnnNNk',
    'knnnnnnnnnnnnnNk',
    'knnnnnnnnnnnnnNk',
    'knnnnnnnnnnnnnNk',
    'knnnnnnnnnnnnnNk',
    'knnnnnnnnnnnnnNk',
    'knnnnnnnnnnnnnNk',
    'knnnnnnnnnnnnnNk',
    'knnnnnnnnnnnnnNk',
    'knnnnnnnnnnnnnNk',
    'knnnnnnnnnnnnnNk',
    'knNnnnnnnnnnnNNk',
    'kNNNNNNNNNNNNNNk',
    'kkkkkkkkkkkkkkkk',
  ],
  brick: [
    'kkkkkkkkkkkkkkkk',
    'rrrrrrrkrrrrrrrk',
    'rqqqqqRkrqqqqqRk',
    'rRRRRRRkrRRRRRRk',
    'kkkkkkkkkkkkkkkk',
    'rrrkrrrrrrrkrrrr',
    'qqRkrqqqqqRkrqqq',
    'RRRkrRRRRRRkrRRR',
    'kkkkkkkkkkkkkkkk',
    'rrrrrrrkrrrrrrrk',
    'rqqqqqRkrqqqqqRk',
    'rRRRRRRkrRRRRRRk',
    'kkkkkkkkkkkkkkkk',
    'rrrkrrrrrrrkrrrr',
    'qqRkrqqqqqRkrqqq',
    'RRRkrRRRRRRkrRRR',
  ],
  rubble: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '.......kk.......',
    '..kk..krRk..kk..',
    '.krRk.kRRk.krqk.',
    'krRRRkkkkkkkRRRk',
    'kkkkkkkkkkkkkkkk',
  ],
  'ground-top': [
    'TTTTTTTTTTTTTTTT',
    'TTTTTTTTTTTTTTTT',
    'tTTtTTTtTTTTtTTt',
    'ttttTttttTtttttt',
    'DtDDtDDDtDDtDDtD',
    'DDDDDDDDDDDDDDDD',
    'DDdDDDDDDDDdDDDD',
    'DDDDDDDDDDDDDDDD',
    'DDDDDdDDDDDDDDdD',
    'DDDDDDDDDDDDDDDD',
    'DdDDDDDDDdDDDDDD',
    'DDDDDDDDDDDDDDDD',
    'DDDDDDDdDDDDDDDD',
    'DDDDDDDDDDDDdDDD',
    'DDdDDDDDDDDDDDDD',
    'DDDDDDDDDDDDDDDD',
  ],
  'ground-fill': [
    'DDDDDDDDDDDDDDDD',
    'DDDdDDDDDDDDDDDD',
    'DDDDDDDDDDdDDDDD',
    'DDDDDDDDDDDDDDDD',
    'DDDDDDdDDDDDDDDd',
    'DDDDDDDDDDDDDDDD',
    'DdDDDDDDDDDDDDDD',
    'DDDDDDDDDdDDDDDD',
    'DDDDDDDDDDDDDDDD',
    'DDDDdDDDDDDDDdDD',
    'DDDDDDDDDDDDDDDD',
    'DDDDDDDDDDDDDDDD',
    'DDDDDDDdDDDDDDDD',
    'DdDDDDDDDDDDDDDD',
    'DDDDDDDDDDDDdDDD',
    'DDDDDDDDDDDDDDDD',
  ],
  'pipe-top': [
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    'kghgggggggggggggggggggggggggGhGk',
    'kghgggggggggggggggggggggggggGhGk',
    'kghgggggggggggggggggggggggggGhGk',
    'kghgggggggggggggggggggggggggGhGk',
    'kghgggggggggggggggggggggggggGhGk',
    'kghgggggggggggggggggggggggggGhGk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    '..kghggggggggggggggggggggGhGk...',
    '..kghggggggggggggggggggggGhGk...',
    '..kghggggggggggggggggggggGhGk...',
    '..kghggggggggggggggggggggGhGk...',
    '..kghggggggggggggggggggggGhGk...',
    '..kghggggggggggggggggggggGhGk...',
    '..kghggggggggggggggggggggGhGk...',
    '..kghggggggggggggggggggggGhGk...',
  ],
  'pipe-body': [
    '..kghggggggggggggggggggggGhGk...',
    '..kghggggggggggggggggggggGhGk...',
    '..kghggggggggggggggggggggGhGk...',
    '..kghggggggggggggggggggggGhGk...',
    '..kghggggggggggggggggggggGhGk...',
    '..kghggggggggggggggggggggGhGk...',
    '..kghggggggggggggggggggggGhGk...',
    '..kghggggggggggggggggggggGhGk...',
    '..kghggggggggggggggggggggGhGk...',
    '..kghggggggggggggggggggggGhGk...',
    '..kghggggggggggggggggggggGhGk...',
    '..kghggggggggggggggggggggGhGk...',
    '..kghggggggggggggggggggggGhGk...',
    '..kghggggggggggggggggggggGhGk...',
    '..kghggggggggggggggggggggGhGk...',
    '..kghggggggggggggggggggggGhGk...',
  ],
  plant: [
    '....kkk..kkk....',
    '...krrrkkrrrk...',
    '..krrwrrrrwrrk..',
    '..krrrrrrrrrrk..',
    '..kwkwkwkwkwkk..',
    '..kkwkwkwkwkwk..',
    '..krrrrrrrrrrk..',
    '...krrwrrwrrk...',
    '....kkkkkkkk....',
    '.......kg.......',
    '..kkk..kg..kkk..',
    '.kgggk.kg.kgggk.',
    '..kgggkkgkgggk..',
    '...kkggkggkkk...',
    '......kggk......',
    '.......kg.......',
  ],
  critter: [
    '................',
    '................',
    '................',
    '.....kkkkkk.....',
    '...kkppppppkk...',
    '..kppppppppppk..',
    '..kpwwppppwwpk..',
    '.kppwkppppkwppk.',
    '.kppkkppppkkppk.',
    '.kpppppppppppPk.',
    '.kpppkkkkkkppPk.',
    '.kPppkwwwwkpPPk.',
    '..kPPPPPPPPPPk..',
    '...kkkkkkkkkk...',
    '..kNNk....kNNk..',
    '..kkkk....kkkk..',
  ],
  'critter-flat': [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '.kppwkppppkwppk.',
    '.kPPPPPPPPPPPPk.',
    'kNNkkkkkkkkkkNNk',
    'kkkk........kkkk',
  ],
  'sign-q': [
    '.kkkkkkkkkkkkkk.',
    'knnnnnnnnnnnnnnk',
    'knnnnnkkkknnnnNk',
    'knnnnkwwwwknnnNk',
    'knnnnkwkkwknnnNk',
    'knnnnnkkkwknnnNk',
    'knnnnnnkwwknnnNk',
    'knnnnnnkwknnnnNk',
    'knnnnnnnkknnnnNk',
    'knnnnnnkwknnnnNk',
    'knnnnnnnkknnnnNk',
    'kNNNNNNNNNNNNNNk',
    '.kkkkkkkkkkkkkk.',
    '......kNNk......',
    '......kNNk......',
    '......kNNk......',
  ],
  'sign-ok': [
    '.kkkkkkkkkkkkkk.',
    'knnnnnnnnnnnnnnk',
    'knnnnnnnnnnnknNk',
    'knnnnnnnnnnkgkNk',
    'knnnnnnnnnkggkNk',
    'knnnnnnnnkggknNk',
    'knnkknnnkggknnNk',
    'knkggknkggknnnNk',
    'knnkggkggknnnnNk',
    'knnnkgggknnnnnNk',
    'knnnnkkknnnnnnNk',
    'kNNNNNNNNNNNNNNk',
    '.kkkkkkkkkkkkkk.',
    '......kNNk......',
    '......kNNk......',
    '......kNNk......',
  ],
  post: [
    '......kNNk......',
    '......kNNk......',
    '......kNNk......',
    '......kNNk......',
    '......kNNk......',
    '......kNNk......',
    '......kNNk......',
    '......kNNk......',
    '......kNNk......',
    '......kNNk......',
    '......kNNk......',
    '......kNNk......',
    '......kNNk......',
    '.....kNNNNk.....',
    '....kNNNNNNk....',
    '....kkkkkkkk....',
  ],
  pole: [
    '.......kk.......',
    '.......kk.......',
    '.......kk.......',
    '.......kk.......',
    '.......kk.......',
    '.......kk.......',
    '.......kk.......',
    '.......kk.......',
    '.......kk.......',
    '.......kk.......',
    '.......kk.......',
    '.......kk.......',
    '.......kk.......',
    '.......kk.......',
    '.......kk.......',
    '.......kk.......',
  ],
  'pole-top': [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '......kkkk......',
    '.....kuyyyk.....',
    '.....kyyyYk.....',
    '.....kyyYYk.....',
    '......kkkk......',
    '.......kk.......',
    '.......kk.......',
    '.......kk.......',
    '.......kk.......',
    '.......kk.......',
  ],
  flag: [
    'kkkkkkkkkkkk....',
    'kggggggggggggk..',
    'kgggwwgggggggggk',
    'kggwwwwgggggggk.',
    'kgggwwgggggggk..',
    'kgggggggggggk...',
    'kggggggggggk....',
    'kkkkkkkkkkk.....',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  'flag-grey': [
    'kkkkkkkkkkkk....',
    'kmmmmmmmmmmmmk..',
    'kmmmmmmmmmmmmmmk',
    'kmmmmmmmmmmmmmk.',
    'kmmmmmmmmmmmmk..',
    'kmmmmmmmmmmmk...',
    'kmmmmmmmmmmk....',
    'kkkkkkkkkkk.....',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  coin: [
    '................',
    '.....kkkkkk.....',
    '....kuuyyyYk....',
    '...kuyyyyyyYk...',
    '...kuyyuYyyYk...',
    '...kuyyuYyyYk...',
    '...kuyyuYyyYk...',
    '...kuyyuYyyYk...',
    '...kuyyuYyyYk...',
    '...kuyyuYyyYk...',
    '...kuyyyyyyYk...',
    '....kYYYYYYk....',
    '.....kkkkkk.....',
    '................',
    '................',
    '................',
  ],
  'coin-ghost': [
    '................',
    '.....mmmmmm.....',
    '....m......m....',
    '...m........m...',
    '...m........m...',
    '...m........m...',
    '...m........m...',
    '...m........m...',
    '...m........m...',
    '...m........m...',
    '...m........m...',
    '....m......m....',
    '.....mmmmmm.....',
    '................',
    '................',
    '................',
  ],
  star: [
    '.......kk.......',
    '......kuuk......',
    '......kuyk......',
    '.....kuyyYk.....',
    'kkkkkkuyyyYkkkkk',
    'kuuuuuyyyyyyyYYk',
    '.kuyyykyyykyyYk.',
    '..kuyykyyykyYk..',
    '...kuyyyyyyYk...',
    '...kuyyyyyyYk...',
    '..kuyyyYYyyyYk..',
    '..kuyyYkkYyyYk..',
    '.kuyyYk..kYyyYk.',
    '.kuyYk....kYyYk.',
    '.kkkk......kkkk.',
    '................',
  ],
  'star-empty': [
    '.......kk.......',
    '......kmmk......',
    '......kmmk......',
    '.....kmmmmk.....',
    'kkkkkkmmmmmkkkkk',
    'kmmmmmmmmmmmmmmk',
    '.kmmmmmmmmmmmmk.',
    '..kmmmmmmmmmmk..',
    '...kmmmmmmmmk...',
    '...kmmmmmmmmk...',
    '..kmmmmmmmmmmk..',
    '..kmmmmkkmmmmk..',
    '.kmmmmk..kmmmmk.',
    '.kmmmk....kmmmk.',
    '.kkkk......kkkk.',
    '................',
  ],
  cloud: [
    '................................',
    '............kkkkkk..............',
    '..........kkwwwwwwkk............',
    '.........kwwwwwwwwwwk...kkkk....',
    '.....kkkkwwwwwwwwwwwwkkkwwwwk...',
    '....kwwwwwwwwwwwwwwwwwwwwwwwwk..',
    '...kwwwwwwwwwwwwwwwwwwwwwwwwwwk.',
    '..kwwwwwwwwwwwwwwwwwwwwwwwwwwwk.',
    '.kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwk',
    '.kwwwwwwwwwwwwwwwwwwwwwwwwwwwwlk',
    '.kwwwwwwwwwwwwwwwwwwwwwwwwwwwllk',
    '..kllwwwwwwwwwwwwwwwwwwwwwwlllk.',
    '...kllllllwwwwwwwwwwwwwllllllk..',
    '....kkkkkkkkkkkkkkkkkkkkkkkkk...',
    '................................',
    '................................',
  ],
  bush: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '..........kkkkk.................',
    '........kkgggggkk.....kkkk......',
    '.......kggggggggggk..kggggkk....',
    '......kgggggggggggkkkggggggk....',
    '.....kggggggggggggggggggggggk...',
    '....kgggggghgggggggggghgggggk...',
    '...kgggggghhggggggggghhggggggk..',
    '..kggggghhhgggggggghhhggggggggk.',
    '.kgggggggggggggggggggggggggggggk',
    '.khhhhhhhhhhhhhhhhhhhhhhhhhhhhhk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
  ],
  node: [
    '................',
    '.....kkkkkk.....',
    '...kkyyyyyykk...',
    '..kyuuyyyyyyYk..',
    '..kyuyyyyyyyYk..',
    '.kyuyyyyyyyyyYk.',
    '.kyyyyyyyyyyyYk.',
    '.kyyyyyyyyyyyYk.',
    '.kyyyyyyyyyyyYk.',
    '.kyyyyyyyyyyyYk.',
    '..kyyyyyyyyyYk..',
    '..kYyyyyyyyYYk..',
    '...kkYYYYYYkk...',
    '.....kkkkkk.....',
    '................',
    '................',
  ],
  'node-clear': [
    '................',
    '.....kkkkkk.....',
    '...kkggggggkk...',
    '..kggggggggggk..',
    '..kgggggggkwgk..',
    '.kgggggggkwwghk.',
    '.kggkkgggkwwghk.',
    '.kgkwwkgkwwgghk.',
    '.kggkwwkwwggghk.',
    '.kgggkwwwgggghk.',
    '..kggggkggggghk.',
    '..khgggggggghk..',
    '...kkhhhhhhkk...',
    '.....kkkkkk.....',
    '................',
    '................',
  ],
  'node-lock': [
    '................',
    '.....kkkkkk.....',
    '...kkmmmmmmkk...',
    '..kmmmmmmmmmmk..',
    '..kmmmmkkmmmmk..',
    '.kmmmmkmmkmmmMk.',
    '.kmmmmkmmkmmmMk.',
    '.kmmmkkkkkkmmMk.',
    '.kmmmkyyyykmmMk.',
    '.kmmmkykkykmmMk.',
    '..kmmkyyyykmMk..',
    '..kMmkkkkkkMMk..',
    '...kkMMMMMMkk...',
    '.....kkkkkk.....',
    '................',
    '................',
  ],
  'node-active': [
    '................',
    '.....kkkkkk.....',
    '...kkooooookk...',
    '..kouuooooooRk..',
    '..kouooooooooRk.',
    '.kouoookkooooRk.',
    '.kooookwwkoooRk.',
    '.koookwwwwkooRk.',
    '.koookwwwwkooRk.',
    '.kooookwwkoooRk.',
    '..koooookkooRk..',
    '..kRoooooooRRk..',
    '...kkRRRRRRkk...',
    '.....kkkkkk.....',
    '................',
    '................',
  ],
  'warp-pipe': [
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    'kpqpppppppppppppppppppppppppPqPk',
    'kpqpppppppppppppppppppppppppPqPk',
    'kpqpppppppppppppppppppppppppPqPk',
    'kpqpppppppppppppppppppppppppPqPk',
    'kpqpppppppppppppppppppppppppPqPk',
    'kpqpppppppppppppppppppppppppPqPk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    '..kpqpppppppppppppppppppPqPk....',
    '..kpqpppppppppppppppppppPqPk....',
    '..kpqpppppppppppppppppppPqPk....',
    '..kpqpppppppppppppppppppPqPk....',
    '..kpqpppppppppppppppppppPqPk....',
    '..kpqpppppppppppppppppppPqPk....',
    '..kpqpppppppppppppppppppPqPk....',
    '..kpqpppppppppppppppppppPqPk....',
  ],
  'arrow-down': [
    '......kkkk......',
    '......kuuk......',
    '......kuuk......',
    '......kuuk......',
    '......kuuk......',
    '..kkkkkuukkkkk..',
    '...kuuuuuuuuk...',
    '....kuuuuuuk....',
    '.....kuuuuk.....',
    '......kuuk......',
    '.......kk.......',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  'arrow-up': [
    '.......kk.......',
    '......kuuk......',
    '.....kuuuuk.....',
    '....kuuuuuuk....',
    '...kuuuuuuuuk...',
    '..kkkkkuukkkkk..',
    '......kuuk......',
    '......kuuk......',
    '......kuuk......',
    '......kuuk......',
    '......kkkk......',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  'cloud-ride': [
    '................................',
    '............kkkkkk..............',
    '..........kkwwwwwwkk............',
    '.........kwwwwwwwwwwk...kkkk....',
    '.....kkkkwwwwwwwwwwwwkkkwwwwk...',
    '....kwwwwwwwwwwwwwwwwwwwwwwwwk..',
    '...kwwwwwwwkkwwwwwwkkwwwwwwwwwk.',
    '..kwwwwwwwwkkwwwwwwkkwwwwwwwwwk.',
    '.kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwk',
    '.kwwwwwwqqwwwwwwwwwwwwqqwwwwwwlk',
    '.kwwwwwwwwwwwkkkkkwwwwwwwwwwwllk',
    '..kllwwwwwwwwwwwwwwwwwwwwwwlllk.',
    '...kllllllwwwwwwwwwwwwwllllllk..',
    '....kkkkkkkkkkkkkkkkkkkkkkkkk...',
    '................................',
    '................................',
  ],
  sparkle: [
    '.......u........',
    '.......u........',
    '......uwu.......',
    '...uuuwwwuuu....',
    '......uwu.......',
    '.......u........',
    '.......u........',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
};
