import type { HeroId } from '@quest/shared';
import { parseLine, type DialogueLine } from '../ui/dialogue';

/** Non-game things that can be jammed in the console (the easter egg). */
export type JunkKind =
  | 'sock'
  | 'snack'
  | 'soda'
  | 'juice'
  | 'pizza'
  | 'comic'
  | 'controller'
  | 'cassette'
  | 'banana'
  | 'duck'
  | 'donut'
  | 'teddy'
  | 'yoyo'
  | 'gamebook';
export const JUNK_KINDS: JunkKind[] = ['sock', 'snack', 'soda', 'juice', 'pizza', 'comic', 'controller', 'cassette', 'banana', 'duck', 'donut', 'teddy', 'yoyo', 'gamebook'];
/** Kinds with words printed on them, filled in as `{label}`. */
export const LABELLED_KINDS: JunkKind[] = ['snack', 'comic', 'cassette', 'gamebook'];

/**
 * What the player's hero says after putting something that isn't a game in
 * the console. First person, in that hero's own voice, which comes from their
 * style and personality: never from background, identity or accent.
 *
 * Each line starts with its mood: `+` happy, `=` meh, `!` shocked, `-` sad.
 * Meh and shocked lines get the "reacting" portrait. One *keyword* per line
 * is highlighted. `{label}` is the snack's brand, the comic's sound word, the
 * tape's title or the gamebook's title; `{game}` is the title on the TV, so a
 * line can react to whichever of the kind's screens came up. Five lines per hero per kind;
 * `any` is the fallback for kinds added later.
 */
const LINES: Record<HeroId, Record<JunkKind | 'any', string[]>> = {
  classic: {
    sock: [
      "+Wahoo! ...wait, that's a *sock*. Wahoo anyway!",
      "!Oh no, that's a *sock*! Let's go anyway!",
      '+One sock, one slot, one *adventure*!',
      "+{game}! I'm gonna *win* this one!",
      '+Every hero needs a *sidekick*. Even a sock!',
    ],
    snack: [
      '+{label}! A *power-up* in a bag!',
      '+If I eat it in the console, does it count as *1-UP*?',
      '!Oh no! The {label} went in the *wrong pipe*!',
      "+{game}! Let's *jump* in!",
      '!The crumbs are *jumping* higher than me!',
    ],
    soda: [
      '+A can! I bet it does a *super jump*!',
      '!Fizzing! The console is *fizzing*!',
      "+Shake it, slot it, *let's go*!",
      '+{game}! *Full speed* ahead!',
      '+Fizz power! I feel *invincible*!',
    ],
    juice: [
      '!Uh-oh. The console is *swimming* now.',
      "+It's an *underwater level*!",
      '-I just wanted to save my *progress*...',
      '+{game}! Hold your *breath*!',
      '+Swim, swim, *swim*! Wahoo!',
    ],
    pizza: [
      '+Pizza! The *best* cartridge!',
      "!It's got a *topping* stuck in the pins!",
      '+Extra cheese, extra *lives*!',
      '+{game}! Race you to the *crust*!',
      '+Pepperoni *power-up*! Wahoo!',
    ],
    comic: [
      '+{label}! It looks like a *game* already!',
      "+I'm in the *comic* now! Wahoo!",
      "!Hey, the *pages* don't press START!",
      "+{game}! I've read the *ending*!",
      '+Comic heroes are *heroes* too!',
    ],
    controller: [
      '!A controller in the console? *Player zero*?',
      "+It's controlling *itself*! Amazing!",
      '=Hmm. Who is *playing* who?',
      "+{game}! I'll take *player two*!",
      '!It pressed START by *itself*!',
    ],
    cassette: [
      '+{label}! Wahoo, *music*!',
      '+{game}! Turn it *up*!',
      '!The tape is *unspooling*! Uh-oh!',
      '+A rocking *soundtrack* for my adventure!',
      "=Hmm. It's *rewinding*. Forever.",
    ],
    banana: [
      '!Whoa! *Slippery* level!',
      "+{game}! I'll *dodge* the peel!",
      '+Bananas! The *best* bonus fruit!',
      '-I always *slip* on these...',
      '+One banana, one *big* jump!',
    ],
    duck: [
      '+A duck! *Quack*-a-hoo!',
      "+{game}! Ducks can't *fly* like me!",
      '!It squeaked at me! *Rude*!',
      '+Rubber duck *rescue* mission!',
      '+Bath time *bonus* stage!',
    ],
    donut: [
      "+A donut! It's a *warp ring*!",
      '+{game}! Through the *hole*!',
      '!It rolled away! *Come back*!',
      '+Sprinkles are like *coins*!',
      '+Extra glaze, extra *lives*!',
    ],
    teddy: [
      "+Teddy's coming on the *adventure*!",
      '+{game}! Go, *Teddy*, go!',
      "-Don't worry, Teddy, I'll *save* you!",
      '+The softest *hero* ever!',
      "!Teddy's *bigger* than me now!",
    ],
    yoyo: [
      '+Yo-yo! *Up* and down!',
      '+{game}! Spin to *win*!',
      "!It's all *tangled*! Oh no!",
      '+Around the *world*! Wahoo!',
      '+Best *rope* swing ever!',
    ],
    gamebook: [
      '+{label}! I choose *adventure*!',
      '+{game}! Roll the *dice*!',
      '!Page 3 and I fell in a *pit*!',
      '+Fight the *dragon*? Wahoo, yes!',
      '+Finger in the page, just in *case*!',
    ],
    any: [
      '+Wahoo! *Something* went in!',
      "+Let's see what *happens*!",
      "!That's not a *cartridge*! ...Let's go!",
    ],
  },
  bearded: {
    sock: [
      "=Well. That's one way to *darn* a sock.",
      '=I *sigh* in sixteen bits.',
      "-This is why we can't have *nice* consoles.",
      "={game}. They'll make a *sequel*, too.",
      '=Odd socks, odd *choices*.',
    ],
    snack: [
      '={label}. Saving it for *later*, apparently.',
      '=Crisps in the slot. *Crunch* time.',
      '-I was going to *eat* that.',
      '={game}. Sounds about *right*.',
      '-There goes my *snack* drawer.',
    ],
    soda: [
      '=Soda. Bit *flat*, as a game.',
      "=It's a can-do *attitude*. Literally.",
      '-That was my last *fizzy* one.',
      "={game}. Can't *wait* for the reviews.",
      "=It's a bit *pop* culture.",
    ],
    juice: [
      '=Juice. Now the console is *sticky* too.',
      "-I'll get the *mop*.",
      '=That one was *concentrated* foolishness.',
      '={game}. Very *refreshing* title.',
      '=Pulp *fiction*, really.',
    ],
    pizza: [
      "=Pizza. That's a *slice* of life I didn't need.",
      "=It doesn't *fit*. It never fits.",
      '-Well, there goes *tea*.',
      "={game}. I'd rather just *eat* it.",
      "+All right. That's a good *one*.",
    ],
    comic: [
      '={label}. As in my *back*, bending to fix this.',
      "=It's a graphic *novel* approach.",
      '+Fine. That was *quite* funny.',
      '={game}. A sequel *nobody* asked for.',
      '=Bit *two-dimensional*.',
    ],
    controller: [
      '=Controller in the console. Very *self-aware*.',
      "=I'm not *mad*. I'm impressed.",
      '+A classic *dad* move, to be fair.',
      "={game}. Who's *counting*?",
      "=I'll go and get the *spare*.",
    ],
    cassette: [
      '={label}. I made you that *tape*.',
      '={game}. Very *retro*.',
      "-It's eaten the *tape*. Of course.",
      '=Rewind with a *pencil*, like the old days.',
      "+Fine. That's a *banger*.",
    ],
    banana: [
      '=A banana. *Peel* good about this?',
      '={game}. Ripe for a *sequel*.',
      '-I was going to have that with *breakfast*.',
      "=It's a *slippery* slope.",
      '+All right. That got a *smile*.',
    ],
    duck: [
      '=A duck. *Quack* on.',
      '={game}. Fowl *play*.',
      "=I'll call it a *debug* session.",
      "-That duck's *seen* things.",
      "+Fine. That's *quacking* good.",
    ],
    donut: [
      '=Donut *worry* about it.',
      '={game}. Hole-y *moly*.',
      '-That was the *last* one.',
      "=There's a *hole* in this plan.",
      "+I'll allow it. *Glazed* and confused.",
    ],
    teddy: [
      "=Teddy's in the *console*. Naturally.",
      '={game}. *Bear* with me.',
      '-I *bought* you that bear.',
      '=Unbearably *silly*.',
      "+All right, that's *sweet*.",
    ],
    yoyo: [
      '=Yo-yo. *Up* and down, like my mood.',
      '={game}. *Strings* attached.',
      "-It's *knotted* now.",
      '=Walk the *dog*, they said.',
      '+Fine. *Nice* spin.',
    ],
    gamebook: [
      '={label}. I *cheated* at this one as a kid.',
      '={game}. Thrilling. Roll a *six*.',
      '-Dead on page 3. *Again*.',
      '=Keep a finger in the *page*. Trust me.',
      '+Fine. The *dragon* art is good.',
    ],
    any: [
      '=Well. That *happened*.',
      '-I just *cleaned* that.',
      "=Let's call it a *feature*.",
    ],
  },
  redhead: {
    sock: [
      "+Honestly? Best thing that console's *played* all year.",
      '+One sock *short* of a pair, one game richer.',
      '=The sock *chose* this. I respect it.',
      "+{game}? I'd *play* that.",
      '+Honestly, the sock *suits* it.',
    ],
    snack: [
      '+{label} edition. *Limited* release.',
      '+Crunchy *graphics*. Love it.',
      '=Bit *crumby* on the loading screen.',
      '+{game}. Big *vibes*.',
      '=Crumbly, but *charming*.',
    ],
    soda: [
      '+Fizzy launch, *zero* regrets.',
      '+A *carbonated* classic.',
      "=It's mostly *bubbles*, but so am I.",
      '+{game}. Sounds *iconic*.',
      '+Bubbles on the *big* screen.',
    ],
    juice: [
      '+Juice level! Very *refreshing*.',
      "=Sure, it's leaking. It's *fine*.",
      '+The TV smells *fruity* now.',
      '+{game}. Very *summer*.',
      '=A little *sticky*. Fine.',
    ],
    pizza: [
      '+Pizza in the slot. *Vibes*.',
      "+Honestly, it's an *improvement*.",
      '=Cold pizza runs *smoother*.',
      '+{game}. *Sign* me up.',
      '+Best *slice* of the day.',
    ],
    comic: [
      '+{label}! Way more *plot* than most games.',
      '+Two-player *reading* mode.',
      "=I'll wait for the *movie*.",
      '+{game}. *Cult* classic.',
      "+Plot twist: it's *great*.",
    ],
    controller: [
      "+Controller-ception. *Chef's kiss*.",
      "=It's playing itself. *Relatable*.",
      '+No hands *needed*. Love that.',
      '+{game}. *Cosy*.',
      "=It's controlling *me* now.",
    ],
    cassette: [
      '+{label}! *Road trip* tape.',
      '+{game}. *Volume* up.',
      "=It's *warbly*. Love it.",
      '+Side B is the *good* side.',
      '=It ate the tape. *Whatever*.',
    ],
    banana: [
      '+A banana. *Sure*.',
      '+{game}. Totally *bananas*.',
      '=Bit *bruised*. Like me.',
      "+It's *ripe* for this.",
      '=Mind the *peel*.',
    ],
    duck: [
      '+Duck! *Iconic*.',
      '+{game}. *Splashy*.',
      '=Squeaky, but *unbothered*.',
      '+Bath time, *bonus* round.',
      '+Ducks just *get* it.',
    ],
    donut: [
      '+Donut in the slot. *Mood*.',
      '+{game}. *Sweet*.',
      '=A bit *sticky*. Worth it.',
      '+Sprinkles make *everything* better.',
      "=There's a *hole* in it. Relatable.",
    ],
    teddy: [
      "+Teddy's *living* his dream.",
      '+{game}. *Adorable*.',
      '=He looks a bit *squished*.',
      '+Softest *player* ever.',
      '+Teddy *wins*, obviously.',
    ],
    yoyo: [
      '+Yo-yo. *Easy* breezy.',
      '+{game}. *Spinny*.',
      "=It's *tangled*. Classic.",
      '+Up, down, *whatever*.',
      '+Smooth *trick*.',
    ],
    gamebook: [
      '+{label}! Skip to the *ending*, honestly.',
      '+{game}. No *map*, no stress.',
      '=Fell in a pit. *Lovely*.',
      '+I always pick the *scary* door.',
      '=Lost the pencil. Making up my *stats*.',
    ],
    any: [
      '+Sure, why *not*?',
      '+Chaos looks *good* on that console.',
      '=Eh. It *works*. Kind of.',
    ],
  },
  'mustard-jumper': {
    sock: [
      '!To be clear, socks are not a *supported* format. I checked.',
      '=The manual says *nothing* about socks. I read it twice.',
      '!That voids the *warranty*. Probably. I should check.',
      '!{game} is not a *licensed* title. I checked.',
      '=I have *concerns* about the fit.',
    ],
    snack: [
      '!{label} is a *snack*, not a cartridge. I have notes.',
      '=There are crumbs in the *contacts* now. Seventeen, roughly.',
      '-I labelled that bag *specifically*.',
      '!{game}? The *crumb* count alone...',
      "=I'll need to *vacuum* the slot.",
    ],
    soda: [
      '!Liquids near electronics is *risk* number one on my list.',
      '=Technically it is *aluminium*. Technically.',
      '!Is it supposed to *hiss* like that?',
      '!{game} implies *pressurised* contents.',
      '=Note: *carbonation* is not a feature.',
    ],
    juice: [
      '!Juice! In the console! I need a *towel* and a plan.',
      '-I did a *risk assessment* for exactly this.',
      '=On the bright side, it is *vitamin* C.',
      "!{game}. That's a *spill* hazard in the title.",
      "=I'm *documenting* this.",
    ],
    pizza: [
      '!That slice is at least three times the *slot* width.',
      '=The cheese has bridged the *pins*. Interesting. Bad, but interesting.',
      '-I was told this was a *pizza*-free zone.',
      '!{game} contains *grease*. I can tell.',
      '=Technically a *triangle* is a valid shape.',
    ],
    comic: [
      '={label}. The *page* count is not compatible.',
      '!Paper in a slot is a *fire* hazard. Probably.',
      '+To be fair, it does have a *story* mode.',
      '=The {game} *rating* is unclear.',
      '!Paper cuts are a *real* risk.',
    ],
    controller: [
      '!A controller cannot control *itself*. Can it? I need to check.',
      '=That is a *loop*. I dislike loops.',
      '!Who is player one *now*?',
      '!{game} has no *input* method now.',
      "=I'll draw a *diagram* of this.",
    ],
    cassette: [
      '!{label} is *magnetic* tape. In a cartridge slot!',
      '={game}. The *format* is wrong.',
      '!If it unspools I *cannot* rewind it.',
      '=I labelled that *tape* by hand.',
      '+To be fair, it does have *side B*.',
    ],
    banana: [
      '!A banana is a *slip* hazard. Literally.',
      "={game}. I'd *rate* it unsafe.",
      "!It's *bruising*. I can see it bruising.",
      '=Potassium is not a *file* format.',
      '-I was saving that for *ten fifteen*.',
    ],
    duck: [
      '!The duck is *not* waterproofed for this.',
      "={game}. I'm *nervous*.",
      "=Technically it's a *bath* accessory.",
      '!Did it just *squeak* at me?',
      '+Okay, it *is* debugging-shaped.',
    ],
    donut: [
      '!Icing on the *contacts*!',
      "={game}. There's a *hole* in the logic.",
      '=The sprinkles are *uncountable*. I tried.',
      "!That's a *choking* hazard for the console.",
      '-My *emergency* donut.',
    ],
    teddy: [
      '!Teddy is *not* rated for electronics.',
      "={game}. I'm *worried* about him.",
      "-He's been through a *lot*.",
      "=I'll check his *stitching* after.",
      '+He does look *brave*.',
    ],
    yoyo: [
      '!The string could *snag* the pins.',
      '={game}. Very *unstable*.',
      "=I measured the string. It's too *long*.",
      "!It's *spinning*. Why is it spinning?",
      '-It took me ages to *untangle*.',
    ],
    gamebook: [
      '!{label} is a *book*. Books are not cartridges.',
      '={game}. I have the *errata*, if needed.',
      '=To be clear, you roll *two* dice for that.',
      '!You cannot just *flip* back. That is cheating.',
      '+To be fair, the *rules* are on page 1.',
    ],
    any: [
      '!That is *not* in the spec.',
      '=I will add this to the *FAQ*.',
      '-I did *warn* everyone.',
    ],
  },
  'denim-jacket': {
    sock: [
      "+It's not a bug, it's an *installation*.",
      '+Sock in console. I call it *Untitled #3*.',
      '=Mixed *media*. Very mixed.',
      '+{game}: a *retrospective*.',
      '+The sock is the *medium*.',
    ],
    snack: [
      '+{label}: a study in *crunch*.',
      '+The crumbs are the *brushstrokes*.',
      '=Very pop art. Very *salty*.',
      '+{game}. Very *pop* art.',
      '+Crisp packet *collage*.',
    ],
    soda: [
      '+Soda can, console, *found object*.',
      '+The fizz is the *soundtrack*.',
      '=Bit *derivative*. Still nice.',
      '+{game}. The can is the *canvas*.',
      '=Very *readymade*.',
    ],
    juice: [
      '+A juice *wash*. Bold palette.',
      '=Is it *art* if it drips? Yes.',
      '+The puddle is part of the *piece*.',
      '+{game}. Fluid *storytelling*.',
      '+Juice as *watercolour*.',
    ],
    pizza: [
      '+Pizza on circuit board. *Gallery* ready.',
      '+Melted cheese, *texture* goals.',
      "=I'd title it *Cold Slice*.",
      '+{game}. A *still life*. Moving.',
      '+Cheese *sculpture*.',
    ],
    comic: [
      "+{label}! Now *that's* a composition.",
      "+Comic meets console. It's a *collab*.",
      '=The panels need more *negative* space.',
      '+{game}. *Panel* show.',
      '+Ink meets *pixels*.',
    ],
    controller: [
      '+A controller playing a controller. *Meta* art.',
      '+Very *recursive*. Very now.',
      '=It needs a *frame*. Or a fuse.',
      '+{game}. Interactive *piece*.',
      "=It's *about* control.",
    ],
    cassette: [
      '+{label}. A *mixtape* is a portrait.',
      '+{game}. Sound *installation*.',
      '=The hiss is part of the *texture*.',
      '+Analogue *warmth*.',
      '=Very *lo-fi*. Very me.',
    ],
    banana: [
      '+A banana. *Gallery* classic.',
      '+{game}. Very *conceptual*.',
      '=Ripe for *interpretation*.',
      '+The brown spots are the *detail*.',
      '=Bit *derivative*, bananas.',
    ],
    duck: [
      '+Duck as *muse*.',
      '+{game}. *Pop* surreal.',
      '=Very *yellow* period.',
      '+The squeak is the *soundtrack*.',
      '=Mixed *media*: rubber, chaos.',
    ],
    donut: [
      '+A donut. *Circular* composition.',
      '+{game}. The hole is the *point*.',
      '+Sprinkles as *pointillism*.',
      '=Icing, *impasto*.',
      '=Very *sweet*. Too sweet?',
    ],
    teddy: [
      '+Teddy as *portrait*.',
      '+{game}. *Soft* sculpture.',
      '=Very *nostalgic* piece.',
      '+Plush *minimalism*.',
      '=Bit *sentimental*. I like it.',
    ],
    yoyo: [
      '+Yo-yo: *kinetic* art.',
      '+{game}. Motion *study*.',
      '=The string is a *line* drawing.',
      '+Very *Op* art, spinning.',
      '=Tangled *composition*.',
    ],
    gamebook: [
      '+{label}. The *cover* art is a whole mood.',
      '+{game}. Interactive *fiction* as a medium.',
      '=Pencil maps in the margins. *Mixed* media.',
      '+The reader is the *artist* here.',
      '=Very *ink* heavy. I respect it.',
    ],
    any: [
      '+Everything is *art* if you squint.',
      "+I'm calling it a *happening*.",
      '=Hmm. *Interesting* choice.',
    ],
  },
  hoodie: {
    sock: [
      '+Any% sock glitch. New world *record*.',
      '+Skipped the whole game with one *sock*. Frame perfect.',
      '=Gonna need a *reset*.',
      '+{game}. *Any%* route found.',
      '+Sock clip, *no* damage.',
    ],
    snack: [
      '+{label} skip! Saves *four* seconds.',
      '+Crisp *clip* through the slot. Nice.',
      '=Lost a *frame* on the crunch.',
      '+{game}. *Sub*-ten run.',
      '=Crumbs cost me a *frame*.',
    ],
    soda: [
      '+Soda boost. *Speed* tech.',
      '+Can launch *strat*. Wild.',
      "!That's a *softlock*. Probably.",
      '+{game}. *Boost* strat.',
      '+Fizz *skip* unlocked.',
    ],
    juice: [
      '=Water level. Worst *level*.',
      '!Juice got into the *RNG*.',
      '-Run *killed* by juice.',
      '={game}. *Slow* water physics.',
      '-Juice *reset*. Again.',
    ],
    pizza: [
      '+Pizza *pause* buffer. Big brain.',
      '+Slice clip. *Out of bounds*!',
      "=It's not optimal but it's *tasty*.",
      '+{game}. *Cheese* skip.',
      '+Slice *zip*. Clean.',
    ],
    comic: [
      '+Speedrunning *literature*. {label}!',
      '+Skipped every *cutscene*.',
      '=Reading is a *slow* category.',
      '+{game}. *Skip* all dialogue.',
      '+Panel *clip*!',
    ],
    controller: [
      '+TAS *mode*. It plays itself.',
      '+Controller in console. *Tool*-assisted.',
      '!Two inputs, *zero* hands.',
      '+{game}. *Input* display on.',
      '+Controller *macro*. Legal?',
    ],
    cassette: [
      '+{label}. Running *music*.',
      '+{game}. *Rewind* glitch!',
      '=Tape *lag*.',
      '+Side B *skip*.',
      '!It ate the *tape*. Run dead.',
    ],
    banana: [
      '+Banana *clip*!',
      '+{game}. *Slide* tech.',
      '!Slipped on the *peel*. Classic.',
      '+Peel *boost*.',
      '=Banana *RNG*.',
    ],
    duck: [
      '+Duck *glitch*!',
      '+{game}. Quack *skip*.',
      '=Squeak *lag*.',
      '+Float *tech*.',
      '!The duck *clipped* through!',
    ],
    donut: [
      '+Donut *warp*!',
      '+{game}. *Loop* skip.',
      '=Sprinkle *RNG*.',
      '+Glaze *slide*.',
      '!It rolled *out of bounds*!',
    ],
    teddy: [
      '+Teddy *any%*.',
      '+{game}. *Hug* skip.',
      '=Soft *lock*. Literally.',
      '+Plush *clip*.',
      '!Teddy got the *world record*!',
    ],
    yoyo: [
      '+Yo-yo *grapple* tech.',
      '+{game}. *Swing* skip.',
      '=String *desync*.',
      '+Spin *cancel*.',
      '!It *zipped* back!',
    ],
    gamebook: [
      '+{label}. Page 1 to 400, *any%*.',
      '+{game}. Skip every *fight*.',
      '!Died on page 3. *Reset*.',
      '+Finger in the page is a *save state*.',
      '=Dice *RNG*. Pain.',
    ],
    any: [
      '+New *category* just dropped.',
      '+GG. *Frame* perfect.',
      '=Reset the *run*.',
    ],
  },
  emo: {
    sock: [
      '-Even the console rejects me. ...*Same*, console. Same.',
      '-A lone sock, *forgotten*. I know the feeling.',
      '+Okay that was *kind of* great.',
      '-{game}. A *tragedy* in one sock.',
      '+Okay, {game} is actually *good*.',
    ],
    snack: [
      "-{label}. It's not a game, it's a *cry* for help.",
      '+Crunchy *despair*. My favourite.',
      '-Even the crisps feel *empty*.',
      '-{game}. Everything *crumbles*.',
      "+Fine. I'd *play* {game}.",
    ],
    soda: [
      '-Flat. Like my *heart*.',
      '+It fizzed. It *felt* something.',
      '=The console is *bitter* now.',
      '-{game}. The fizz *fades*.',
      '+Okay, the rocket bit is *cool*.',
    ],
    juice: [
      '-The console *weeps* juice.',
      '-Sticky, like my *memories*.',
      '+Okay, the drip trail is *very* aesthetic.',
      '-{game}. Drowning in *feelings*.',
      '=Even the fish looks *sad*.',
    ],
    pizza: [
      '-Pizza, cold as the *world*.',
      '+Folded in half. *Relatable*.',
      '=No one *understands* pizza like I do.',
      '-{game}. Cold, like *everything*.',
      '+Okay, the slice *won*. Good for it.',
    ],
    comic: [
      '-{label}... nobody hears the *panels* scream.',
      "+The hero's sad backstory *slaps*.",
      '-My life in *black and white*.',
      '-{game}. Heroes always *leave*.',
      '+The art style *slaps*.',
    ],
    controller: [
      '-A controller, *controlled*. Like us all.',
      "+That's *deep*, actually.",
      '-Player one has left the *chat*.',
      '-{game}. No one *chose* me either.',
      '=Even the controller has *issues*.',
    ],
    cassette: [
      '-{label}. Every song is about *me*.',
      '-{game}. Side B is all *sad* songs.',
      '+Okay this *mixtape* slaps.',
      '-The tape *unravels*. Like me.',
      '=Rewinding to the *sad* bit.',
    ],
    banana: [
      '-A banana. Bruised *inside*.',
      '-{game}. Everyone *slips*.',
      '+Okay, the peel physics are *great*.',
      '=Even fruit goes *brown*.',
      "-It's *split*. Like my heart.",
    ],
    duck: [
      '-The duck *floats*. I sink.',
      '-{game}. Lonely *bathtub*.',
      '+Okay the squeak is *cute*.',
      '=It stares into the *void*.',
      '-Even the duck is *rubber* inside.',
    ],
    donut: [
      '-A donut. *Hollow* in the middle.',
      '-{game}. Sweet, then *gone*.',
      '+Okay, sprinkles are *nice*.',
      "=It's got a *hole*. Like me.",
      '-The last donut. *Typical*.',
    ],
    teddy: [
      '-Teddy *understands* me.',
      '-{game}. He deserves *better*.',
      "+Teddy *won*. I'm crying.",
      "=He's *seen* my diary.",
      '-Hold on, *Teddy*.',
    ],
    yoyo: [
      '-Up and *down*. My life.',
      '-{game}. Always *comes back*. Unlike them.',
      '+Okay that spin is *sick*.',
      '=Hopelessly *tangled*.',
      '-Just a *string* holding on.',
    ],
    gamebook: [
      '-{label}. Every path *ends* in a pit.',
      '-{game}. The dice *hate* me too.',
      '+Okay, the *dragon* is cool. Tell no one.',
      '-I always pick the *wrong* door. Same.',
      '=Turned to page 400. *Still* sad.',
    ],
    any: [
      '-Of course it *did*.',
      '+Fine, that was *fun*. Tell no one.',
      '-This is my *life* now.',
    ],
  },
  goth: {
    sock: [
      '-The sock descends into the *abyss*. As all things must.',
      '=Its pair waits in the *dark*. Forever.',
      '+A fitting *tomb*.',
      '={game}. A *dark* fable.',
      '+The sock rises, *undead*.',
    ],
    snack: [
      '={label}. A feast for the *void*.',
      '+The crisps rest in *peace*.',
      '-The bag is *empty*. Like everything.',
      '={game}. A world of *salt* and shadow.',
      '+Crumbs scatter like *ashes*. Lovely.',
    ],
    soda: [
      '=The bubbles rise. The can *falls*.',
      '+An elegant *hiss*, like a cat in a graveyard.',
      '-The fizz is *dead*. Long live the fizz.',
      '={game}. Fizzing into the *night*.',
      "-The can's *last* breath.",
    ],
    juice: [
      '=The machine drinks. It *thirsts* no more.',
      '+Crimson juice. *Very* fitting.',
      '-Spilled, like *candle* wax at midnight.',
      '={game}. A *flooded* crypt.',
      '+The fish swims in *eternal* dusk.',
    ],
    pizza: [
      '=Pizza: *mortal*, cold, delicious.',
      '+A slice for the *shadows*.',
      "-Even pizza can't escape *entropy*.",
      '={game}. A slice of the *void*.',
      '+Pepperoni, red as *roses*.',
    ],
    comic: [
      '={label}. The hero dies at *dawn*.',
      '+Gothic *panels*. Approved.',
      '-The ink bleeds *dark*. Good.',
      '={game}. The hero is *doomed*.',
      '+Ink black as *midnight*. Approved.',
    ],
    controller: [
      '=The controller *controls* nothing now.',
      '+A haunted *loop*. Lovely.',
      '-Player one is a *ghost*.',
      '={game}. A *haunted* input.',
      '+The machine *plays* alone.',
    ],
    cassette: [
      '={label}. Songs for a *funeral*.',
      '={game}. The tape *remembers*.',
      '+Side B is *darker*. Good.',
      '-The ribbon *unwinds*, like fate.',
      '=Rewind... to the *beginning* of the end.',
    ],
    banana: [
      '=A banana, *wilting* in the dark.',
      '={game}. A slip into *oblivion*.',
      '+Brown spots like *bruised* moons.',
      '-It *rots*. As we all do.',
      '=The peel, a *shroud*.',
    ],
    duck: [
      '=A duck, adrift on a *black* lake.',
      '={game}. It *watches*.',
      '+Its squeak is a *scream*. Lovely.',
      '-It floats. *Alone*.',
      '=A *gothic* bathtub.',
    ],
    donut: [
      '=A circle with an *empty* heart.',
      '={game}. Fall into the *hole*.',
      '+Black icing would be *perfect*.',
      '-Sweetness *fades*.',
      '=It *never* ends, the ring.',
    ],
    teddy: [
      '=Teddy, *guardian* of nightmares.',
      '={game}. He *rules* the dark.',
      '+His button eyes see *everything*.',
      '-Stitched, like an old *wound*.',
      '=A *loyal* familiar.',
    ],
    yoyo: [
      '=It falls, it *returns*. Like a ghost.',
      '={game}. A *pendulum* of doom.',
      '+The spin is *hypnotic*.',
      '-The string will *snap*. One day.',
      '=Down into the *dark*, and back.',
    ],
    gamebook: [
      '={label}. A tome of *doom*. Behold.',
      '={game}. The dice decide our *fate*.',
      '+Death on page 3. *Exquisite*.',
      '=Turn to the page of my *epitaph*.',
      '+A *dragon*. At last, company.',
    ],
    any: [
      '=Into the *dark* it goes.',
      '+How *delightfully* grim.',
      '-Everything ends. Even *that*.',
    ],
  },
  punk: {
    sock: [
      '+No rules! No cartridges! *JUST SOCK!*',
      '+Sock the *system*!',
      "+They said socks don't fit. *Watch me*.",
      '+{game}! *Socks* rule!',
      '+Mismatched and *proud*!',
    ],
    snack: [
      '+{label} riot! *Crunch* the system!',
      '+Crisps in the console! *Anarchy*!',
      '!That bag was *full*. Was.',
      '+{game}! Snacks for *everyone*!',
      '+Crumbs *everywhere*! Good!',
    ],
    soda: [
      '+Shake it up! *Smash* the can!',
      '+Fizz the *establishment*!',
      "!It's *exploding*! Brilliant!",
      '+{game}! *Blast* off!',
      '+Shake it *harder*!',
    ],
    juice: [
      '+Juice *revolution*!',
      "!It's *leaking*! Even better!",
      '+No towels! *No surrender*!',
      '+{game}! *Flood* the system!',
      '+Sticky *rebellion*!',
    ],
    pizza: [
      "+Pizza in the console! The man *can't stop* us!",
      '+Extra cheese, extra *rebellion*!',
      '+Folded and *proud*!',
      '+{game}! *Slice* the rules!',
      '+Pineapple *on it*! Fight me!',
    ],
    comic: [
      '+{label}! Punk *zine* mode!',
      '+Read it *loud*!',
      '+DIY *game*! Nobody asked!',
      '+{game}! *Punch* the screen!',
      '+Zines over *cartridges*!',
    ],
    controller: [
      '+Controller controls itself! *No masters*!',
      '+Two controllers, *one* rule: none!',
      '!It *unionised*!',
      '+{game}! *No* players!',
      '+Controller *revolt*!',
    ],
    cassette: [
      '+{label}! *Loud* and fast!',
      '+{game}! Three *chords*!',
      '+Home-taped *anarchy*!',
      '!It *chewed* the tape! Punk!',
      '+Side B, *full* volume!',
    ],
    banana: [
      '+Banana *riot*!',
      '+{game}! *Slip* the system!',
      '+Peel *power*!',
      '!It *split*! Brilliant!',
      '+Bruised and *proud*!',
    ],
    duck: [
      '+Duck *uprising*!',
      '+{game}! *Quack* the system!',
      '+Squeak *louder*!',
      '!The duck *bit* back!',
      '+No bath, *no* rules!',
    ],
    donut: [
      '+Donut *anarchy*!',
      '+{game}! Through the *hole*!',
      '+Sprinkles *everywhere*!',
      '!It *rolled* off! Free!',
      '+Glaze the *system*!',
    ],
    teddy: [
      '+Teddy *riot*!',
      '+{game}! Bears *bite* back!',
      '+Patched and *punk*!',
      "!Teddy's got a *mohawk* now!",
      '+No more *bedtime*!',
    ],
    yoyo: [
      '+Yo-yo *mosh*!',
      '+{game}! *Spin* it!',
      '+Tangled and *loud*!',
      '!It *snapped* back! Yes!',
      '+Up the *yo-yos*!',
    ],
    gamebook: [
      '+{label}! *Rip* up the rules!',
      '+{game}! Roll it *loud*!',
      '+I fight the *dragon*! Every time!',
      '!Turn to 400? I turn to *any* page!',
      '+Dice? *Watch* me cheat!',
    ],
    any: [
      '+No rules! *Just this*!',
      '+Break the *slot*!',
      '!It went *in*! Amazing!',
    ],
  },
  'rainbow-tee': {
    sock: [
      "+Yes, sock! Look at you go! You're a *game* now!",
      '+Sock, you *did it*!',
      "+Sock's *main character* era!",
      '+{game}! The sock *earned* this!',
      '+Look at that *star*!',
    ],
    snack: [
      '+{label}, you *superstar*!',
      '+Crisps getting the *spotlight*! Love!',
      '+Best *snack* debut ever!',
      '+{game}! The crisps are *shining*!',
      '+Snack *icon*!',
    ],
    soda: [
      '+Go, soda, *go*!',
      '+Fizzy and *fabulous*!',
      "+That can's a *natural*!",
      '+{game}! *Go*, can!',
      '+So *proud* of that fizz!',
    ],
    juice: [
      '+Juice is *living* its best life!',
      '+Splash *zone*! Amazing!',
      '=Okay, a *bit* messy. Still proud!',
      '+{game}! *Splash* star!',
      '+That fish is *thriving*!',
    ],
    pizza: [
      '+Pizza slice, *icon*!',
      '+So proud of that *pizza*!',
      '+Ten out of ten *slice*!',
      '+{game}! Slice of *champions*!',
      '+Cheese *legend*!',
    ],
    comic: [
      '+{label}! *Stunning* debut!',
      '+The comic is *thriving*!',
      '+Front page *material*!',
      '+{game}! *Front* page!',
      '+That hero is *glowing*!',
    ],
    controller: [
      '+Two controllers? *Teamwork*!',
      '+It believes in *itself*!',
      '+Controller *support* group!',
      '+{game}! *Teamwork* makes the dream work!',
      '+Both controllers *win*!',
    ],
    cassette: [
      '+{label}! *Banger* mix!',
      '+{game}! Tape, you *star*!',
      '+Every track a *hit*!',
      '+Rewind it! *Again*!',
      "=It's *warbly*, but proud!",
    ],
    banana: [
      '+Banana, *superstar*!',
      '+{game}! *Peel* of approval!',
      '+Look at it *go*!',
      '+Best *fruit* ever!',
      '=Okay, a bit *brown*. Still proud!',
    ],
    duck: [
      "+Duck, you're *amazing*!",
      '+{game}! *Quack* star!',
      '+Squeak of *victory*!',
      '+The duck is *thriving*!',
      '+Best *bath* buddy!',
    ],
    donut: [
      '+Donut, *icon*!',
      '+{game}! *Sweet* win!',
      '+Sprinkle *party*!',
      '+So *glazed*, so proud!',
      '+Ring of *champions*!',
    ],
    teddy: [
      '+Teddy, *hero*!',
      '+{game}! Go, *Teddy*!',
      '+Biggest *hug* award!',
      "+Teddy's *main character* era!",
      '+So *proud* of you, bear!',
    ],
    yoyo: [
      '+Yo-yo, *legend*!',
      '+{game}! *Spin* queen!',
      '+Look at it *return*!',
      '+Best *trick* ever!',
      '+String *superstar*!',
    ],
    gamebook: [
      '+{label}! You chose *courage*!',
      '+{game}! Roll that *twenty*!',
      '+Every page a *plot twist*!',
      '+You beat the *dragon*, book!',
      '=Back to page 1, but *proud*!',
    ],
    any: [
      '+You go, *thing*!',
      "+That's the *spirit*!",
      '+So *proud* of you, random object!',
    ],
  },
  'trans-flag-hair': {
    sock: [
      '+Go on, little sock, live your *dream*.',
      '+Every sock deserves a *quest*.',
      '+Wave goodbye to the *drawer*!',
      '+{game}! The little sock is *brave*!',
      '+Off you go, *adventurer*!',
    ],
    snack: [
      '+{label}, off on an *adventure*!',
      '+Hello, crisps! *Welcome* to the castle!',
      '=Bye, crisps. I barely *knew* you.',
      '+{game}! Have *fun*, crisps!',
      '+Wave to the *crumbs*!',
    ],
    soda: [
      '+Little can, *big* dreams!',
      '+Fly, soda, *fly*!',
      '=You were *fizzier* than this, once.',
      '+{game}! Up, up and *away*!',
      '+Fly *safe*, little can!',
    ],
    juice: [
      '+Juice, you get a *bath* in there!',
      '-Oh no, *sticky* little console!',
      '+Swim, juice, *swim*!',
      '+{game}! Say hi to the *fish*!',
      '-Oh, sticky little *buttons*!',
    ],
    pizza: [
      '+Pizza wants to be a *hero*!',
      "+Hello, slice! Don't be *scared*!",
      '+A *cheesy* new beginning!',
      '+{game}! Go *win* it, slice!',
      '+Good *luck*, pepperoni!',
    ],
    comic: [
      '+{label}! The comic *gets* it.',
      '+Comic, meet *console*. Be friends!',
      '+A *story* inside a story!',
      '+{game}! A brand new *chapter*!',
      '+The hero *jumped* out to say hi!',
    ],
    controller: [
      '+Look, they found a *friend*!',
      '+Controller *family* reunion!',
      '+Aww, it wants to *play* too!',
      '+{game}! Best *friends* forever!',
      "+They're *holding* hands!",
    ],
    cassette: [
      '+{label}! *Sing* for me!',
      '+{game}! A little tape, a big *stage*!',
      '+Hello, *side B*!',
      '-Oh no, little *ribbon*!',
      '+Play my *favourite* one!',
    ],
    banana: [
      '+Little banana, *off* you go!',
      "+{game}! Don't *slip*!",
      "+You're so *yellow* and nice!",
      '-Oh, a *bruise*. Poor thing.',
      '+Have an *adventure*, banana!',
    ],
    duck: [
      '+Hello, *ducky*!',
      '+{game}! Swim, *ducky*!',
      '+Squeak *hello*!',
      '+Little duck, big *dreams*!',
      "-Don't *sink*, little duck!",
    ],
    donut: [
      '+Little donut, *roll* on!',
      '+{game}! Sweet *dreams*!',
      '+Sprinkles say *hi*!',
      "-Oh, you're a bit *squished*!",
      '+Find the *warp*, donut!',
    ],
    teddy: [
      "+Teddy's off on a *quest*!",
      "+{game}! You've got *this*, Teddy!",
      '+Give everyone a *hug*!',
      '-Come *home* safe, Teddy!',
      '+Teddy, the *bravest* bear!',
    ],
    yoyo: [
      '+Wheee, little *yo-yo*!',
      '+{game}! *Spin* for joy!',
      '+Come *back*, yo-yo!',
      '-Oh no, *tangles*!',
      '+Twirly *friend*!',
    ],
    gamebook: [
      '+{label}! Off you go, little *book*!',
      '+{game}! Be *brave* in there!',
      '+The dragon just wants a *friend*!',
      '-Oh no, not the *pit*, little book!',
      '+Every path can be a *good* one!',
    ],
    any: [
      '+Good *luck* in there!',
      '+Be *brave*, little thing!',
      '=Oh! Hello, *you*!',
    ],
  },
  'trans-pin': {
    sock: [
      "=I've made worse *decisions*. Not many, but some.",
      '+Well, it *fits*. Sort of.',
      '=The sock looks *calm*. More than me.',
      "={game}. I'd give it *three* stars.",
      "+It's a *quiet* hit.",
    ],
    snack: [
      "={label}. We'll call it a *tasting* menu.",
      "+There's a *crumb* of logic to it.",
      '=I was saving those for *Friday*.',
      '={game}. A *crunchy* premise.',
      '+Honestly, *charming*.',
    ],
    soda: [
      '=Gently does *it*. Too late.',
      "+Fizz. Well. That's *something*.",
      '=Note to self: *cans* are not games.',
      '={game}. Light on *plot*.',
      '+Fizzy, but *fair*.',
    ],
    juice: [
      '-I had *one* job.',
      "=It's fine. Juice is *mostly* water.",
      '+Well, the console *smells* nice.',
      "={game}. It'll *dry*. Eventually.",
      '+The fish has *range*.',
    ],
    pizza: [
      '=The pizza *insisted*.',
      "+Honestly, it's the best *meal* that console's had.",
      "=Let's not *mention* this.",
      "={game}. I'd *watch* that.",
      '+Solid *slice*.',
    ],
    comic: [
      '+{label}. Fair *point*, comic.',
      '=Bit of light *reading* for the console.',
      '+A quiet *classic*.',
      '={game}. Seen *worse*.',
      '+Good *pacing*.',
    ],
    controller: [
      '=Who controls the *controller*? Philosophy.',
      '+It looks *happier* in there.',
      "=I'll just *unplug* myself.",
      '={game}. Very *meta*.',
      '+Calm *gameplay*.',
    ],
    cassette: [
      '={label}. I *remember* this one.',
      '={game}. Easy *listening*.',
      '+A *decent* mix.',
      '=Bit of *tape* hiss. Fine.',
      "-I'll *rewind* it later.",
    ],
    banana: [
      '=A banana. *Fair* enough.',
      '={game}. Mild *peril*.',
      '+Nicely *ripe*.',
      '=Mind the *step*.',
      '-That was my *lunch*.',
    ],
    duck: [
      '=A duck. Very *calm*.',
      '={game}. Gentle *chaos*.',
      "+It's a good *listener*.",
      '=Squeaks *politely*.',
      '+Steady *duck*.',
    ],
    donut: [
      '=A donut. *Reasonable*.',
      '={game}. Sweet *enough*.',
      '+Nice *sprinkles*.',
      '=One *bite* missing. Not me.',
      '-I was *saving* that.',
    ],
    teddy: [
      '=Teddy looks *content*.',
      '={game}. Quietly *heroic*.',
      '+Good *bear*.',
      '=Bit *squashed*. Bearable.',
      "+He's *earned* this.",
    ],
    yoyo: [
      '=A yo-yo. *Classic*.',
      '={game}. Gentle *swing*.',
      '+Nice *return*.',
      '=Tangled. *Typical*.',
      '+Smooth *enough*.',
    ],
    gamebook: [
      '={label}. Take your *time* choosing.',
      '={game}. Quietly *tense*.',
      '+A *steady* roll.',
      "=Back to page 1. That's *fine*.",
      '+Good *choice*, that door.',
    ],
    any: [
      '=Well. That *happened*.',
      '+Could be *worse*.',
      '=Quietly *impressive*.',
    ],
  },
  'bi-bomber': {
    sock: [
      "+Sock in the slot. Nobody's ever done it like *this*.",
      '+Smooth *insert*. Clean.',
      '+First try. *Obviously*.',
      '+{game}. *Instant* classic.',
      '+Sock, but make it *cool*.',
    ],
    snack: [
      '+{label} drop. *Exclusive*.',
      '+Crisp in, *no* crumbs. Skill.',
      '+Limited *edition* move.',
      '+{game}. *Effortless*.',
      '+Crisp *style*.',
    ],
    soda: [
      '+Can in the console. *Iconic*.',
      '+Effortless *fizz*.',
      "=Didn't even *spill*. Mostly.",
      '+{game}. Smooth *launch*.',
      '+Fizz, *no sweat*.',
    ],
    juice: [
      '+Splash with *style*.',
      "=It's leaking, but *fashionably*.",
      '+Juice, *nailed* it.',
      '+{game}. *Splash* in style.',
      '=Sticky, but *suave*.',
    ],
    pizza: [
      '+Pizza slot? *Signature* move.',
      '+Folded it in one *motion*.',
      '+Never been *done*. Until now.',
      '+{game}. *Pole* position.',
      '+One slice, *one* take.',
    ],
    comic: [
      '+{label}. *Cover* star.',
      '+Comic in, *cool* out.',
      '+That was *cinema*.',
      '+{game}. *Box office*.',
      '+Cover *star* energy.',
    ],
    controller: [
      '+Controller on controller. *Power* move.',
      '+Even the console is *impressed*.',
      '+One-handed. *Easy*.',
      '+{game}. *Flawless* victory.',
      '+Pad on pad. *Clean*.',
    ],
    cassette: [
      '+{label}. Curated *mix*.',
      '+{game}. *Headliner*.',
      '+Side B, *still* fire.',
      '=A little *hiss*. Vintage.',
      '+Pressed play like a *pro*.',
    ],
    banana: [
      '+Banana, *nailed* it.',
      '+{game}. *Slick*.',
      '+No slip. *Skill*.',
      '=A bit *brown*. Still cool.',
      '+Peel *drop*. Clean.',
    ],
    duck: [
      '+Duck. *Iconic*.',
      '+{game}. *Cool* quack.',
      '+Smooth *float*.',
      '+Squeak with *style*.',
      '+First *try*.',
    ],
    donut: [
      '+Donut *dunk*.',
      '+{game}. *Sweet* move.',
      '+Glazed and *amazed*.',
      '+Ring *toss*. Perfect.',
      '=Sprinkles *everywhere*. Fine.',
    ],
    teddy: [
      '+Teddy, *legend*.',
      '+{game}. *Main event*.',
      '+Cuddle *champion*.',
      '+Smooth *hug*.',
      '=Bit *squished*. Still iconic.',
    ],
    yoyo: [
      '+Yo-yo *trick*. Easy.',
      '+{game}. *Flawless* spin.',
      '+Walked the *dog*.',
      '+Around the *world*. Done.',
      '=Tangle? *Intentional*.',
    ],
    gamebook: [
      '+{label}. Beat it on the *first* read.',
      '+{game}. Natural *twenty*. Obviously.',
      '+Dragon down. *Smooth*.',
      '=Fell in a pit. *Stylishly*.',
      '+Never needed a finger in the *page*.',
    ],
    any: [
      '+*Nailed* it.',
      '+Clean. *Smooth*. Done.',
      "+You're *welcome*, console.",
    ],
  },
  'drag-glam': {
    sock: [
      '!A sock, darling? In THIS *economy*? Iconic.',
      '+The sock is *serving*.',
      '!Bold. *Brave*. A little bit wrong.',
      '+{game}! Darling, the *drama*!',
      '!A sock with a *storyline*!',
    ],
    snack: [
      '+{label}, darling, you are *stunning*.',
      '+Crunchy *couture*.',
      '!Crumbs on the *runway*?!',
      '+{game}! *Delicious* entrance!',
      '!The crumbs, darling, the *crumbs*!',
    ],
    soda: [
      '+Fizz, sparkle, *glamour*.',
      '+The can gave a *performance*.',
      '!Bubbles everywhere! *Encore*!',
      '+{game}! *Sparkle* and fizz!',
      '!An *explosive* debut!',
    ],
    juice: [
      '!Darling, the juice is *everywhere*.',
      '+A splash *entrance*. Love.',
      '+Very *wet look*. Very now.',
      '+{game}! A *splash* finale!',
      "!Darling, I'm *drenched*!",
    ],
    pizza: [
      '+Pizza slice, *fierce*.',
      '!Folded? Darling, we do *drama*.',
      '+Extra cheese is a *lifestyle*.',
      '+{game}! *Cheesy* glamour!',
      "!She's *folding* under pressure!",
    ],
    comic: [
      '+{label}! Give me panels, give me *story*.',
      '+The comic is *giving* hero.',
      '!The plot *thickens*, darling.',
      '+{game}! A *starring* role!',
      '!The *twist*, darling!',
    ],
    controller: [
      '+A controller inside a controller? Very *meta*, very fashion.',
      '+Double the *drama*.',
      '!It plays *itself*? Iconic.',
      '+{game}! *Double* act!',
      "!It's *upstaged* itself!",
    ],
    cassette: [
      '+{label}! Play my *entrance* music!',
      '+{game}! Live and *fabulous*!',
      "!It's eating the tape! *Drama*!",
      '+Side B is my *encore*.',
      '+A *diva* mixtape.',
    ],
    banana: [
      '+A banana, darling! *Iconic* curve.',
      '+{game}! *Slip* into something fabulous!',
      '!She *slipped*! On stage!',
      '+Yellow is *this season*.',
      '!Bruised? *Never*.',
    ],
    duck: [
      '+A duck, darling! *Rubber* chic.',
      '+{game}! *Splash* entrance!',
      '!It *squeaked* at me! Rude!',
      '+Ducks are *fashion*.',
      '+Float like a *queen*.',
    ],
    donut: [
      '+A donut, darling! *Glazed* perfection.',
      '+{game}! *Sprinkle* me!',
      '!Icing on the *runway*!',
      '+Ring around the *glamour*.',
      '+Sweet *sensation*!',
    ],
    teddy: [
      "+Teddy, darling, you're a *star*!",
      '+{game}! *Plush* royalty!',
      "!He's *crushing* it!",
      '+Cuddly *couture*.',
      '+A *fabulous* bear.',
    ],
    yoyo: [
      '+Yo-yo, darling! *Twirl*!',
      '+{game}! Spin *glamour*!',
      "!It's *tangled*! Scandal!",
      '+Up, down, *serve*!',
      '+A spin for the *ages*.',
    ],
    gamebook: [
      '+{label}! Darling, what a *title*!',
      '+{game}! Roll for *drama*!',
      '!A pit! How *scandalous*!',
      '+The dragon is *serving* menace.',
      '+Choose your own *entrance*, darling.',
    ],
    any: [
      '+Darling, *iconic*.',
      '!Gasp! *Scandalous*!',
      '+A *moment*. Truly.',
    ],
  },
  'nb-beanie': {
    sock: [
      "=Is it a game if it's a sock? Is *anything*?",
      "=Socks: the console's *existential* crisis.",
      '+Maybe the sock was the *quest* all along.',
      '={game}. A sock *reflecting* on itself.',
      '+Even socks have *journeys*.',
    ],
    snack: [
      '={label}: a game *about* snacking. Or the other way round.',
      '=If crisps fall in a console, do they make a *sound*?',
      '+Snack as *metaphor*. Got it.',
      '={game}. What *is* a world, really?',
      '+Snack *mindfully*.',
    ],
    soda: [
      '=The can is half *full*. Of console.',
      '+Bubbles are just *tiny* questions.',
      '=Fizz is temporary. Like *everything*.',
      '={game}. All fizz is *fleeting*.',
      '+Bubbles rise. *Interesting*.',
    ],
    juice: [
      '=Where does the juice *end* and the console begin?',
      '-Some spills are *permanent*.',
      '+Fluid *identity*, console.',
      '={game}. The fish *contemplates* the flood.',
      '+Flow with *it*.',
    ],
    pizza: [
      '=Is a folded slice still a *slice*?',
      '+Pizza: the original *open world*.',
      '=Hmm. Cheese as *interface*.',
      '={game}. A *slice* of meaning.',
      '+Triangles are *honest*.',
    ],
    comic: [
      '={label}. Words are just *noise* until you read them.',
      '+A comic in a console. *Layers*.',
      "=Who's reading *whom*?",
      '={game}. A story *about* stories.',
      '+Panels are just *moments*.',
    ],
    controller: [
      '=If it controls itself, is it *free*?',
      '+Nice *loop*. Very zen.',
      '!Wait. Am I the *controller*?',
      '={game}. Who plays *whom*?',
      '+A *loop* of intent.',
    ],
    cassette: [
      '={label}. Memory on *tape*.',
      '={game}. Rewind is just *remembering*.',
      '+Side B is the *other* view.',
      '=Tape *hiss* is honest.',
      '-Some songs *stretch*.',
    ],
    banana: [
      '=A banana. A *curve* of possibility.',
      '={game}. Every slip *teaches*.',
      '+Ripeness is *timing*.',
      '=Is a peel a *shell*?',
      "-It's *browning*. Like all things.",
    ],
    duck: [
      '=The duck *floats*. Effortlessly.',
      '={game}. Rubber *zen*.',
      "+Ducks don't *overthink*.",
      '=A squeak is a *thought*.',
      '+Debugging by *listening*.',
    ],
    donut: [
      '=A donut: the shape of *nothing*.',
      '={game}. The hole *holds* it.',
      '+Sprinkles are *small joys*.',
      '=Is it a ring or a *cake*?',
      '-Sweetness, *briefly*.',
    ],
    teddy: [
      '=Teddy, *patient* as ever.',
      '={game}. Softness as *strength*.',
      '+He was always *there*.',
      '=Who *comforts* the bear?',
      '+A *quiet* hero.',
    ],
    yoyo: [
      '=It *always* returns.',
      '={game}. Cycles, *cycles*.',
      '+A spin is *balance*.',
      '=Tangles are just *knots* in time.',
      '!Wait. Am *I* the yo-yo?',
    ],
    gamebook: [
      '={label}. Did I choose, or did the *book*?',
      '={game}. Free will, in *dice*.',
      '=Every page holds the *others*.',
      "+Turn to 400. Or *don't*.",
      '-Some doors stay *closed*.',
    ],
    any: [
      '=Interesting. Or is *it*?',
      '+Sure. *Why not*?',
      "=Let's sit with *that*.",
    ],
  },
  'hijab-skater': {
    sock: [
      '+Kickflip into the cartridge slot. Stuck the *landing*!',
      '+Sock *grind*! Clean!',
      '+Ten points for *style*!',
      '+{game}! Big *air*!',
      '+Sock *slide*, landed!',
    ],
    snack: [
      '+{label} *ollie*! Big air!',
      '+Crisp *bail*, but cool!',
      '+Smooth *drop-in*!',
      '+{game}! *Grind* the rail!',
      '+Crisp *kickflip*!',
    ],
    soda: [
      '+Can *launch*! Huge!',
      '+Soda *slide*, nailed it!',
      '!It *rolled* off! Again!',
      '+{game}! *Launch* ramp!',
      '+Can *carve*!',
    ],
    juice: [
      '!Juice *wipeout*!',
      '+Splash *combo*!',
      '=Slippery *landing*. Respect.',
      '+{game}! *Splash* landing!',
      '!Slipped in the *puddle*!',
    ],
    pizza: [
      '+Pizza *manual* into the slot!',
      '+Slice *spin*, full rotation!',
      '+Cheese grab! *Sick*!',
      '+{game}! Slice *grind*!',
      '+Cheese *combo*!',
    ],
    comic: [
      '+{label}! *Trick* of the day!',
      '+Comic *flip*!',
      '+Read it mid-*air*!',
      '+{game}! *Bonus* points!',
      '+Panel *pop*!',
    ],
    controller: [
      '+Controller *combo*! Double trick!',
      '+Two-pad *rail* slide!',
      '!It landed *itself*!',
      '+{game}! Double *trick*!',
      '+Cable *grind*!',
    ],
    cassette: [
      '+{label}! *Session* soundtrack!',
      '+{game}! Tape *ollie*!',
      '+Side B, *bonus* run!',
      '!It *jammed* mid-trick!',
      '+Rewind, *run* it back!',
    ],
    banana: [
      '+Banana *board*!',
      '+{game}! Peel *slide*!',
      '!Total *wipeout*!',
      '+Curved *ramp*!',
      '+Clean *line*, no slip!',
    ],
    duck: [
      '+Duck *drop-in*!',
      '+{game}! Squeak *spin*!',
      '+Float *trick*!',
      '!Duck *bail*!',
      '+Bath *bowl* session!',
    ],
    donut: [
      '+Donut *bowl*!',
      '+{game}! Ring *grind*!',
      '+Glaze *slide*!',
      '!Rolled *away*!',
      '+360 *spin*!',
    ],
    teddy: [
      '+Teddy *drop-in*!',
      '+{game}! Bear *air*!',
      '+Hug *grab*!',
      '!Teddy *bailed*!',
      '+Plush *landing*!',
    ],
    yoyo: [
      '+Yo-yo *grind*!',
      '+{game}! *Rope* trick!',
      '+Spin *combo*!',
      '!String *snag*!',
      '+Walk the *dog*, landed!',
    ],
    gamebook: [
      '+{label}! *Drop in* to page 1!',
      '+{game}! Dice *kickflip*!',
      '+Jumped the pit, *stuck* the landing!',
      '!Bailed on page *three*!',
      '+Dragon *ollie*!',
    ],
    any: [
      '+Stuck the *landing*!',
      '+Clean *line*!',
      "!That's a *new* trick!",
    ],
  },
  'silver-locs': {
    sock: [
      '+In my day we put the sock on the *foot*. Bold choice.',
      '=The sock had a good *run*, love.',
      "+Well, it's warmer in *there*.",
      "+{game}! Well, that's a *new* one, love.",
      '=Mind you darn it *after*.',
    ],
    snack: [
      "+{label}? That's not a game, love, that's *lunch*.",
      "=You'll want a *plate* for that.",
      '+I used to hide crisps in *drawers*. Same idea.',
      "+{game}? I'll put that on my *list*.",
      '=Crumbs in the *works*, love.',
    ],
    soda: [
      '=Fizzy pop. Rots your *circuits*.',
      '+A can! Very *modern*.',
      '=Back in my day cans had *ring pulls*.',
      '+{game}! Very *exciting*, love.',
      '=Too much *fizz* for me.',
    ],
    juice: [
      "=Juice everywhere. I'll put the *kettle* on.",
      '+Watering the console. It might *grow*.',
      '-That was my good *glass*.',
      '+{game}. Put a *towel* down, love.',
      '=That fish looks *happy* enough.',
    ],
    pizza: [
      "+Pizza in the slot. You'll make a fine *cook* one day.",
      "=Eat it first, love. That's the *trick*.",
      '+Cold pizza: a *classic* for a reason.',
      "+{game}! I'd have a *slice*.",
      "=You'll want a *napkin*.",
    ],
    comic: [
      '+{label}! I had that *issue*.',
      "+Comics. That's *real* reading, that is.",
      "=Mind the *pages*, they're older than you.",
      '+{game}! I read that one *twice*.',
      '=Back in my day comics were *thicker*.',
    ],
    controller: [
      '+A controller playing a controller. *Clever* clogs.',
      '=Even the controller needs a *rest*.',
      "+That's the *family* business.",
      "+{game}! Who's *minding* who?",
      '=Same thing *every* Christmas.',
    ],
    cassette: [
      '+{label}! I *taped* that off the radio.',
      "+{game}! Now *that's* music.",
      '=Fetch me a *pencil*, love.',
      "-It's *eaten* it. They always do.",
      '+Side B was always the *best*.',
    ],
    banana: [
      '+A banana, love. *Good* for you.',
      '+{game}! Mind your *step*.',
      '=Going a bit *spotty*.',
      '-That was for my *porridge*.',
      "+Nature's own *wrapper*.",
    ],
    duck: [
      '+A duck! Bath time, *love*.',
      '+{game}! Very *nautical*.',
      "=It's *squeaking*, bless it.",
      '+You had that in the *bath* for years.',
      '+Quack *away*, then.',
    ],
    donut: [
      '+A donut! *Treat* yourself, love.',
      '+{game}! How *sweet*.',
      '=Sprinkles *everywhere*.',
      '-That was for *afters*.',
      '+Ring-shaped *happiness*.',
    ],
    teddy: [
      "+Teddy! He's been with you *forever*.",
      '+{game}! Mind his *ears*.',
      '=He needs a *wash*, love.',
      '+I *sewed* that eye back on.',
      '-Be *gentle* with him.',
    ],
    yoyo: [
      '+A yo-yo! I had a *wooden* one.',
      '+{game}! Up and *down*, love.',
      "=That's a *knot* and a half.",
      '+Walk the dog, *walk* it!',
      "-I'll *untangle* it later.",
    ],
    gamebook: [
      '+{label}! I had that one, *love*.',
      '+{game}! Roll gently, *dear*.',
      '=In my day we drew the *maps* ourselves.',
      '-Fell in the pit. Mind my *knees*.',
      '+Keep a finger in the *page*, dear.',
    ],
    any: [
      '+Well, I *never*.',
      '=Curious *choice*, love.',
      '+You *always* surprise me.',
    ],
  },
  flannel: {
    sock: [
      '=Tried to fix it with a sock. *Classic* me.',
      '=Sock as a *gasket*. Might hold.',
      "+Sometimes you use what's in the *truck*.",
      '={game}. Good *workmanship*.',
      '+Sock fits. *Mostly*.',
    ],
    snack: [
      '={label}. Field *rations*.',
      '=Crumbs in the *works*. Seen worse.',
      "+It'll do as *packing*.",
      '={game}. *Fuel* for the job.',
      '=Crumb *build-up*. Typical.',
    ],
    soda: [
      '=Can as a *shim*. Rough fix.',
      '+Fizz is just *pressure*. Manageable.',
      '=That will *rust*.',
      '={game}. *Pressure* test passed.',
      '=Should hold till *Friday*.',
    ],
    juice: [
      '-Juice in the *bearings*.',
      '=Needs a *drain* plug.',
      '=Leaks happen. *Patch* it later.',
      '={game}. Needs *bailing* out.',
      '-Water *damage*. Juice damage.',
    ],
    pizza: [
      '=Pizza wedge holding the *slot*. Practical.',
      "+Best *door stop* I've made.",
      '=Cheese as *sealant*. Not ideal.',
      '={game}. Load *bearing* slice.',
      '+Wedged in *tight*.',
    ],
    comic: [
      '={label}. Good *kindling*. Not today.',
      '+Reading the *manual*. Sort of.',
      '=Comic as a *spacer*. Fine.',
      '={game}. Light *reading* on break.',
      '+Decent *spacer*.',
    ],
    controller: [
      '=Spare controller as a *spare part*.',
      '+If it works, it *works*.',
      '=Two of them. *Backup*.',
      '={game}. *Redundant* system.',
      '+Backup *installed*.',
    ],
    cassette: [
      '={label}. *Shop* radio tape.',
      '={game}. Good *sound* for the job.',
      '=Tape *slack*. Tighten it.',
      '+Spare tape as a *shim*.',
      '-Chewed it. *Classic* deck.',
    ],
    banana: [
      '=Banana as a *wedge*. Sure.',
      '={game}. Slip *hazard* noted.',
      '+Good *grip*. Kind of.',
      '=Going *soft*. Not structural.',
      '-That was my *break*.',
    ],
    duck: [
      '=Duck as a *float* valve.',
      '={game}. *Buoyant*.',
      '+Holds *water*. Barely.',
      '=Squeaks. Needs *oil*.',
      '+Good *seal*.',
    ],
    donut: [
      '=Donut as a *gasket*.',
      '={game}. *Ring* seal.',
      '+Fits *round* the pin.',
      '=Sticky. Needs a *wipe*.',
      '-Lost my *snack*.',
    ],
    teddy: [
      '=Teddy as *padding*.',
      '={game}. Good *insulation*.',
      '+Soft *stopper*.',
      '=Seams *holding*.',
      '+Sturdy *bear*.',
    ],
    yoyo: [
      '=Yo-yo string as a *pull cord*.',
      '={game}. Good *tension*.',
      '+Winds *back* fine.',
      '=Knot needs *work*.',
      '+Handy *tool*.',
    ],
    gamebook: [
      '={label} as a *shim*.',
      '={game}. Dice are *square*. Good.',
      '+Good *spine*.',
      '=Pages need a *clamp*.',
      '+Maps the *floor* plan. Handy.',
    ],
    any: [
      '=That should *hold*.',
      '+Rough, but it *works*.',
      '=Tighten it *later*.',
    ],
  },
};

/** A junk line, ready for the dialogue box. */
export type JunkLine = DialogueLine;

/** The raw lines for a hero and kind (falling back to the hero's generic ones). */
export function junkLines(hero: HeroId, kind: string): string[] {
  const lines = LINES[hero] ?? LINES.classic;
  return (lines as Record<string, string[]>)[kind] ?? lines.any;
}

export { parseLine };

/**
 * A line from `hero` about putting `kind` in the console, never the same as
 * `last` (its text) twice running. `fill` has the thing's printed words and
 * the title of the screen that came up.
 */
export function junkLine(
  hero: HeroId,
  kind: string,
  fill: { label?: string; game?: string } = {},
  last?: string,
  r: () => number = Math.random,
): JunkLine {
  const lines = junkLines(hero, kind).map((l) => parseLine(l.replaceAll('{game}', fill.game ?? 'THIS'), fill.label));
  const fresh = lines.length > 1 ? lines.filter((l) => l.text !== last) : lines;
  return fresh[Math.floor(r() * fresh.length)];
}

/** Every hero's raw lines, for tests. */
export const JUNK_LINES = LINES;
